# Generated by Django 2.2.7 on 2019-12-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('photo', models.FileField(upload_to='event/photo/')),
                ('cv', models.FileField(upload_to='event/cv/')),
            ],
        ),
    ]
