# Generated by Django 3.0 on 2019-12-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_remove_registermodel_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='blog_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
