# Generated by Django 2.2.7 on 2019-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0002_auto_20191214_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
