# Generated by Django 3.0 on 2019-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0003_auto_20191214_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
