# Generated by Django 3.0 on 2019-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0004_auto_20191215_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='url',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='blog_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
