# Generated by Django 3.0 on 2019-12-14 12:54

import assignment1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0004_auto_20191214_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='cv',
            field=models.FileField(upload_to='event/cv/', validators=[assignment1.validators.validate_cv_extension]),
        ),
    ]
