# Generated by Django 3.0 on 2019-12-14 12:55

import assignment1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_auto_20191214_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='url',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='blog_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='cv',
            field=models.FileField(blank=True, upload_to='event/cv/', validators=[assignment1.validators.validate_cv_extension]),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='photo',
            field=models.FileField(upload_to='event/photo/', validators=[assignment1.validators.validate_photo_extension]),
        ),
    ]
