# Generated by Django 3.0 on 2019-12-15 16:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0002_filemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
