# Generated by Django 3.0 on 2019-12-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='blog_url',
        ),
    ]
