# Generated by Django 3.0 on 2019-12-15 15:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_auto_20191215_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9594183245', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
