# Generated by Django 3.0 on 2019-12-15 16:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0007_auto_20191215_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='95945585522', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
