# Generated by Django 3.0 on 2019-12-15 16:36

import assignment1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0008_auto_20191215_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.CharField(max_length=15, validators=[assignment1.validators.validate_phone_extension]),
        ),
    ]
