# Generated by Django 3.0 on 2019-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('document_hash', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
