# Generated by Django 2.2.7 on 2019-12-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
