# Generated by Django 3.0 on 2019-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
